networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  postgres:
    image: 'postgres:16.2-alpine'
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: T1OpenSchoolAOP-container
    env_file: .env
    networks:
      - backend
    depends_on:
      - postgres
    environment:
      - HOST=postgres:5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8080:8080'
